apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQWNmTmxHRndpaHN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1Ua3hNakl3TlRoYUZ3MHpOakF5TVRjeE1qSTFOVGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURnMy9OWFM4a2xxUkxqZXhwRUg5SjlLcmlhczlsOGxpeCtwd2JZTXpZODF1ZXJBMUN4WTd1bHNoVVgKQ2VBd3Q4SU1NblBiT0JmVXZMaU5odVZhTnlsWTVtRGMvN2dNU3JlU2h6ckxJTmFGRDFOMkcrTG1PUmRXN2xuWQpzQlFVQVY2ZzhHN1l0aDduR2tuRkNHNlpwWDBoMzllcjRwNjJla1F5cUF2NUVyZUttSjdBWjMyNURVSzdRTUg4CmJsWWo3bzQ5Sk9XdDZZMkJnQlFCNFhjZUdlZFgyS0hXd1F2ZTFqQU5kKzNHaEw3WG9xUFphVFptZlhHYjNvYzUKaWIvMDZmNDdxSzdLak9vTlhzU2ZZaDl6QS9UUnpBcXVzU29SQ2I1RkhpOXI1WHJBd1VvY1VvRVZQaUxWcFRjcwoxNVNYZjFJV1BWclRuY1U4WXpWNXlzRWkvSXNkQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTMzNuS3llN1NBcmZSay9GKzYrOWhkdGNsV216QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjcwcDNEdkxTcgpGQmIrK1RxR3NlMExNSmxYR2NZTXNlSjRwS1ZRdGpVOUdVK2lkcC9yTnkrY2pPeFFPMHFPMFlaNUE5Vm5nTEtwCmhEYndTWXFpM2dFdnZDUE5ia1dXWmZFKzJ2MTJVNVR1Q0tpMUFIalhNekVhZzJGT25GdGVGd1JYdDVUbHdVTDUKT3I5RWtUc3h0OXkydm5FaHpWakpKRk4ySU0rb2QwaEJwS1Jmd3JVZUhYWGtkNk9nQ0tnVlQ5SWtWb0c3NDJzSQorZVFIU3lXaFg1NkovMXd2RWdHRmRwSjU5Syt2U25zU09aaU5Rd0JGb2M5aFV5RmdZai9iekRsaDErWlNNNk43ClBjeXR4aHphYjJ2MG1Lam5remNwRy9Ub0NUalV1QXhNb1R5R0hGVy9FVXhYNXdVNStVejVrVS94UWhBYXhNNGoKM0hVeXVXVS9scjVxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://E78B44ABD099FF86DCD4964C14A599C9.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:691210492006:cluster/my-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:691210492006:cluster/my-cluster
    user: arn:aws:eks:us-east-1:691210492006:cluster/my-cluster
  name: arn:aws:eks:us-east-1:691210492006:cluster/my-cluster
current-context: arn:aws:eks:us-east-1:691210492006:cluster/my-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:691210492006:cluster/my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
